// Super Smash Bros. Quiz Data
// Covering Smash 4 (Wii U/3DS) and Ultimate

export const quizData = {
  characters: {
    easy: [
      { question: "What game is Mario from?", answers: ["super mario bros", "mario bros", "super mario", "mario"], category: "characters" },
      { question: "What game is Link from?", answers: ["the legend of zelda", "legend of zelda", "zelda"], category: "characters" },
      { question: "What game is Pikachu from?", answers: ["pokemon red", "pokemon blue", "pokemon", "pokemon red and blue"], category: "characters" },
      { question: "What game is Kirby from?", answers: ["kirby's dream land", "kirbys dream land", "kirby dream land"], category: "characters" },
      { question: "What game is Donkey Kong from?", answers: ["donkey kong", "donkey kong arcade"], category: "characters" },
      { question: "What game is Samus from?", answers: ["metroid"], category: "characters" },
      { question: "What game is Fox from?", answers: ["star fox", "starfox"], category: "characters" },
      { question: "What game is Yoshi from?", answers: ["super mario world", "mario world"], category: "characters" },
      { question: "What game is Sonic from?", answers: ["sonic the hedgehog", "sonic"], category: "characters" },
      { question: "What game is Pac-Man from?", answers: ["pac-man", "pacman"], category: "characters" },
      { question: "What game is Mega Man from?", answers: ["mega man", "megaman"], category: "characters" },
      { question: "What game is Bowser from?", answers: ["super mario bros", "mario bros", "super mario"], category: "characters" },
      { question: "What game is Peach from?", answers: ["super mario bros", "mario bros", "super mario"], category: "characters" },
      { question: "What game is Zelda from?", answers: ["the legend of zelda", "legend of zelda", "zelda"], category: "characters" },
      { question: "What game is Inkling from?", answers: ["splatoon"], category: "characters" },
    ],
    medium: [
      { question: "What game is Ness from?", answers: ["earthbound", "mother 2"], category: "characters" },
      { question: "What game is Captain Falcon from?", answers: ["f-zero", "f zero"], category: "characters" },
      { question: "What game is Marth from?", answers: ["fire emblem shadow dragon and the blade of light", "fire emblem", "shadow dragon and the blade of light"], category: "characters" },
      { question: "What game is Pit from?", answers: ["kid icarus"], category: "characters" },
      { question: "What game is Olimar from?", answers: ["pikmin"], category: "characters" },
      { question: "What game is Villager from?", answers: ["animal crossing"], category: "characters" },
      { question: "What game is Wii Fit Trainer from?", answers: ["wii fit"], category: "characters" },
      { question: "What game is Little Mac from?", answers: ["punch-out", "punch out"], category: "characters" },
      { question: "What game is Shulk from?", answers: ["xenoblade chronicles"], category: "characters" },
      { question: "What game is Duck Hunt from?", answers: ["duck hunt"], category: "characters" },
      { question: "What game is Ryu from?", answers: ["street fighter", "street fighter 1"], category: "characters" },
      { question: "What game is Cloud from?", answers: ["final fantasy vii", "final fantasy 7", "ff7", "ffvii"], category: "characters" },
      { question: "What game is Bayonetta from?", answers: ["bayonetta"], category: "characters" },
      { question: "What game is Ridley from?", answers: ["metroid"], category: "characters" },
      { question: "What game is King K. Rool from?", answers: ["donkey kong country"], category: "characters" },
      { question: "What game is Isabelle from?", answers: ["animal crossing new leaf", "animal crossing"], category: "characters" },
      { question: "What game is Incineroar from?", answers: ["pokemon sun and moon", "pokemon sun", "pokemon moon"], category: "characters" },
    ],
    hard: [
      { question: "What game is Roy from?", answers: ["fire emblem the binding blade", "fire emblem binding blade", "binding blade"], category: "characters" },
      { question: "What game is Lucas from?", answers: ["mother 3", "earthbound 2"], category: "characters" },
      { question: "What game is Ike from?", answers: ["fire emblem path of radiance"], category: "characters" },
      { question: "What game is Robin from?", answers: ["fire emblem awakening"], category: "characters" },
      { question: "What game is Corrin from?", answers: ["fire emblem fates"], category: "characters" },
      { question: "What game is Richter from?", answers: ["castlevania rondo of blood"], category: "characters" },
      { question: "What game is Simon from?", answers: ["castlevania", "castlevania 1"], category: "characters" },
      { question: "What game is King Dedede from?", answers: ["kirby's dream land", "kirbys dream land"], category: "characters" },
      { question: "What game is Meta Knight from?", answers: ["kirby's adventure", "kirbys adventure"], category: "characters" },
      { question: "What game is Palutena from?", answers: ["kid icarus"], category: "characters" },
      { question: "What game is Dark Pit from?", answers: ["kid icarus uprising"], category: "characters" },
      { question: "What game is Joker from?", answers: ["persona 5"], category: "characters" },
      { question: "What game is Hero from?", answers: ["dragon quest xi", "dragon quest 11"], category: "characters" },
      { question: "What game is Banjo & Kazooie from?", answers: ["banjo-kazooie", "banjo kazooie"], category: "characters" },
      { question: "What game is Terry from?", answers: ["fatal fury", "fatal fury king of fighters"], category: "characters" },
      { question: "What game is Byleth from?", answers: ["fire emblem three houses"], category: "characters" },
      { question: "What game is Min Min from?", answers: ["arms"], category: "characters" },
      { question: "What game is Steve from?", answers: ["minecraft"], category: "characters" },
      { question: "What game is Sephiroth from?", answers: ["final fantasy vii", "final fantasy 7", "ff7", "ffvii"], category: "characters" },
      { question: "What game is Pyra from?", answers: ["xenoblade chronicles 2"], category: "characters" },
    ]
  },
  stages: {
    easy: [
      { question: "What series is Battlefield from?", answers: ["super smash bros", "smash bros", "smash"], category: "stages" },
      { question: "What series is Final Destination from?", answers: ["super smash bros", "smash bros", "smash"], category: "stages" },
      { question: "What game is Peach's Castle from?", answers: ["super mario 64", "mario 64"], category: "stages" },
      { question: "What game is Hyrule Castle from?", answers: ["the legend of zelda ocarina of time", "ocarina of time", "zelda ocarina of time"], category: "stages" },
      { question: "What game is Kongo Jungle from?", answers: ["donkey kong country", "donkey kong 64"], category: "stages" },
      { question: "What series is Pokemon Stadium from?", answers: ["pokemon"], category: "stages" },
      { question: "What game is Mushroom Kingdom from?", answers: ["super mario bros", "mario bros"], category: "stages" },
      { question: "What game is Green Hill Zone from?", answers: ["sonic the hedgehog", "sonic"], category: "stages" },
      { question: "What game is Delfino Plaza from?", answers: ["super mario sunshine", "mario sunshine"], category: "stages" },
      { question: "What series is Yoshi's Island from?", answers: ["yoshi", "super mario"], category: "stages" },
      { question: "What game is Moray Towers from?", answers: ["splatoon", "splatoon 2"], category: "stages" },
      { question: "What game is New Donk City Hall from?", answers: ["super mario odyssey", "mario odyssey"], category: "stages" },
    ],
    medium: [
      { question: "What game is Onett from?", answers: ["earthbound", "mother 2"], category: "stages" },
      { question: "What game is Mute City from?", answers: ["f-zero"], category: "stages" },
      { question: "What game is Corneria from?", answers: ["star fox", "starfox"], category: "stages" },
      { question: "What game is Brinstar from?", answers: ["metroid", "super metroid"], category: "stages" },
      { question: "What game is Fountain of Dreams from?", answers: ["kirby's adventure", "kirbys adventure"], category: "stages" },
      { question: "What game is Skyworld from?", answers: ["kid icarus"], category: "stages" },
      { question: "What game is WarioWare, Inc. from?", answers: ["warioware inc", "warioware"], category: "stages" },
      { question: "What game is Norfair from?", answers: ["metroid"], category: "stages" },
      { question: "What game is Frigate Orpheon from?", answers: ["metroid prime"], category: "stages" },
      { question: "What game is Castle Siege from?", answers: ["fire emblem"], category: "stages" },
      { question: "What game is Distant Planet from?", answers: ["pikmin"], category: "stages" },
      { question: "What game is Skyloft from?", answers: ["the legend of zelda skyward sword", "skyward sword"], category: "stages" },
      { question: "What game is Wii Fit Studio from?", answers: ["wii fit"], category: "stages" },
      { question: "What game is Boxing Ring from?", answers: ["punch-out", "punch out"], category: "stages" },
      { question: "What game is Gaur Plain from?", answers: ["xenoblade chronicles"], category: "stages" },
    ],
    hard: [
      { question: "What game is Suzaku Castle from?", answers: ["street fighter ii", "street fighter 2"], category: "stages" },
      { question: "What game is Midgar from?", answers: ["final fantasy vii", "final fantasy 7", "ff7"], category: "stages" },
      { question: "What game is Umbra Clock Tower from?", answers: ["bayonetta"], category: "stages" },
      { question: "What game is Great Plateau Tower from?", answers: ["the legend of zelda breath of the wild", "breath of the wild"], category: "stages" },
      { question: "What game is New Pork City from?", answers: ["mother 3", "earthbound 2"], category: "stages" },
      { question: "What game is Summit from?", answers: ["ice climber"], category: "stages" },
      { question: "What game is Port Town Aero Dive from?", answers: ["f-zero gx"], category: "stages" },
      { question: "What game is Palutena's Temple from?", answers: ["kid icarus uprising"], category: "stages" },
      { question: "What game is Dracula's Castle from?", answers: ["castlevania"], category: "stages" },
      { question: "What game is Mementos from?", answers: ["persona 5"], category: "stages" },
      { question: "What game is Yggdrasil's Altar from?", answers: ["dragon quest xi", "dragon quest 11"], category: "stages" },
      { question: "What game is Spiral Mountain from?", answers: ["banjo-kazooie", "banjo kazooie"], category: "stages" },
      { question: "What game is King of Fighters Stadium from?", answers: ["king of fighters", "fatal fury"], category: "stages" },
      { question: "What game is Garreg Mach Monastery from?", answers: ["fire emblem three houses"], category: "stages" },
      { question: "What game is Spring Stadium from?", answers: ["arms"], category: "stages" },
      { question: "What game is Minecraft World from?", answers: ["minecraft"], category: "stages" },
      { question: "What game is Northern Cave from?", answers: ["final fantasy vii", "final fantasy 7", "ff7"], category: "stages" },
    ]
  },
  songs: {
    easy: [
      { question: "What game is the song 'Main Theme (Super Smash Bros. Ultimate)' from?", answers: ["super smash bros ultimate", "smash ultimate", "ultimate"], category: "songs" },
      { question: "What game is the song 'Ground Theme (Super Mario Bros.)' from?", answers: ["super mario bros", "mario bros"], category: "songs" },
      { question: "What game is the song 'Main Theme (The Legend of Zelda)' from?", answers: ["the legend of zelda", "legend of zelda", "zelda"], category: "songs" },
      { question: "What game is the song 'Pokemon Center' from?", answers: ["pokemon red and blue", "pokemon red", "pokemon blue", "pokemon"], category: "songs" },
      { question: "What game is the song 'Green Greens' from?", answers: ["kirby's dream land", "kirbys dream land"], category: "songs" },
      { question: "What game is the song 'Corneria' from?", answers: ["star fox", "starfox"], category: "songs" },
      { question: "What game is the song 'Brinstar' from?", answers: ["metroid", "super metroid"], category: "songs" },
      { question: "What game is the song 'Green Hill Zone' from?", answers: ["sonic the hedgehog", "sonic"], category: "songs" },
      { question: "What game is the song 'Mega Man 2 Medley' from?", answers: ["mega man 2", "megaman 2"], category: "songs" },
      { question: "What game is the song 'Splattack!' from?", answers: ["splatoon"], category: "songs" },
      { question: "What game is the song 'Jump Up, Super Star!' from?", answers: ["super mario odyssey", "mario odyssey"], category: "songs" },
    ],
    medium: [
      { question: "What game is the song 'Onett Theme' from?", answers: ["earthbound", "mother 2"], category: "songs" },
      { question: "What game is the song 'Mute City' from?", answers: ["f-zero"], category: "songs" },
      { question: "What game is the song 'Gerudo Valley' from?", answers: ["the legend of zelda ocarina of time", "ocarina of time"], category: "songs" },
      { question: "What game is the song 'Ashley's Song' from?", answers: ["warioware touched", "warioware"], category: "songs" },
      { question: "What game is the song 'Gourmet Race' from?", answers: ["kirby super star", "kirby's fun pak"], category: "songs" },
      { question: "What game is the song 'Title Theme (Animal Crossing)' from?", answers: ["animal crossing"], category: "songs" },
      { question: "What game is the song 'Snowman' from?", answers: ["earthbound", "mother 2"], category: "songs" },
      { question: "What game is the song 'DK Rap' from?", answers: ["donkey kong 64"], category: "songs" },
      { question: "What game is the song 'Fountain of Dreams' from?", answers: ["kirby's adventure", "kirbys adventure"], category: "songs" },
      { question: "What game is the song 'Jungle Level Ver. 2' from?", answers: ["donkey kong country"], category: "songs" },
      { question: "What game is the song 'Tal Tal Heights' from?", answers: ["the legend of zelda link's awakening", "links awakening"], category: "songs" },
      { question: "What game is the song 'Main Theme (Pikmin)' from?", answers: ["pikmin"], category: "songs" },
      { question: "What game is the song 'Wii Fit Plus Medley' from?", answers: ["wii fit plus", "wii fit"], category: "songs" },
    ],
    hard: [
      { question: "What game is the song 'Fire Emblem Theme' from?", answers: ["fire emblem shadow dragon and the blade of light", "fire emblem"], category: "songs" },
      { question: "What game is the song 'Id (Purpose)' from?", answers: ["fire emblem awakening"], category: "songs" },
      { question: "What game is the song 'You Will Know Our Names' from?", answers: ["xenoblade chronicles"], category: "songs" },
      { question: "What game is the song 'Vamprie Killer' from?", answers: ["castlevania"], category: "songs" },
      { question: "What game is the song 'Bloody Tears' from?", answers: ["castlevania ii", "castlevania 2"], category: "songs" },
      { question: "What game is the song 'Last Surprise' from?", answers: ["persona 5"], category: "songs" },
      { question: "What game is the song 'Megalovania' from?", answers: ["undertale"], category: "songs" },
      { question: "What game is the song 'Halland / Dalarna' from?", answers: ["minecraft"], category: "songs" },
      { question: "What game is the song 'Snake Eater' from?", answers: ["metal gear solid 3", "mgs3"], category: "songs" },
      { question: "What game is the song 'Ken Stage' from?", answers: ["street fighter ii", "street fighter 2"], category: "songs" },
      { question: "What game is the song 'Spiral Mountain' from?", answers: ["banjo-kazooie", "banjo kazooie"], category: "songs" },
      { question: "What game is the song 'Battle! (Lorekeeper Zinnia)' from?", answers: ["pokemon omega ruby and alpha sapphire", "pokemon oras"], category: "songs" },
      { question: "What game is the song 'Rooftop Run' from?", answers: ["sonic unleashed"], category: "songs" },
      { question: "What game is the song 'Opening Stage' from?", answers: ["mega man x", "megaman x"], category: "songs" },
      { question: "What game is the song 'Dark Pit's Theme' from?", answers: ["kid icarus uprising"], category: "songs" },
      { question: "What game is the song 'Full Steam Ahead' from?", answers: ["splatoon 2"], category: "songs" },
    ]
  },
  'character-images': {
    easy: [
      { question: "Who is this character?", image: "/images/characters/mario.png", answers: ["mario"], category: "character-images" },
      { question: "Who is this character?", image: "/images/characters/link.png", answers: ["link"], category: "character-images" },
      { question: "Who is this character?", image: "/images/characters/pikachu.png", answers: ["pikachu"], category: "character-images" },
      { question: "Who is this character?", image: "/images/characters/kirby.png", answers: ["kirby"], category: "character-images" },
      { question: "Who is this character?", image: "/images/characters/donkey-kong.png", answers: ["donkey kong", "dk"], category: "character-images" },
      { question: "Who is this character?", image: "/images/characters/samus.png", answers: ["samus", "samus aran"], category: "character-images" },
      { question: "Who is this character?", image: "/images/characters/fox.png", answers: ["fox", "fox mccloud"], category: "character-images" },
      { question: "Who is this character?", image: "/images/characters/yoshi.png", answers: ["yoshi"], category: "character-images" },
      { question: "Who is this character?", image: "/images/characters/sonic.png", answers: ["sonic", "sonic the hedgehog"], category: "character-images" },
      { question: "Who is this character?", image: "/images/characters/bowser.png", answers: ["bowser"], category: "character-images" },
      { question: "Who is this character?", image: "/images/characters/peach.png", answers: ["peach", "princess peach"], category: "character-images" },
      { question: "Who is this character?", image: "/images/characters/zelda.png", answers: ["zelda", "princess zelda"], category: "character-images" },
      { question: "Who is this character?", image: "/images/characters/luigi.png", answers: ["luigi"], category: "character-images" },
      { question: "Who is this character?", image: "/images/characters/inkling.png", answers: ["inkling"], category: "character-images" },
    ],
    medium: [
      { question: "Who is this character?", image: "/images/characters/ness.png", answers: ["ness"], category: "character-images" },
      { question: "Who is this character?", image: "/images/characters/captain-falcon.png", answers: ["captain falcon", "falcon"], category: "character-images" },
      { question: "Who is this character?", image: "/images/characters/marth.png", answers: ["marth"], category: "character-images" },
      { question: "Who is this character?", image: "/images/characters/pit.png", answers: ["pit"], category: "character-images" },
      { question: "Who is this character?", image: "/images/characters/olimar.png", answers: ["olimar", "captain olimar"], category: "character-images" },
      { question: "Who is this character?", image: "/images/characters/villager.png", answers: ["villager"], category: "character-images" },
      { question: "Who is this character?", image: "/images/characters/wii-fit-trainer.png", answers: ["wii fit trainer", "wiifit trainer"], category: "character-images" },
      { question: "Who is this character?", image: "/images/characters/little-mac.png", answers: ["little mac", "mac"], category: "character-images" },
      { question: "Who is this character?", image: "/images/characters/shulk.png", answers: ["shulk"], category: "character-images" },
      { question: "Who is this character?", image: "/images/characters/ryu.png", answers: ["ryu"], category: "character-images" },
      { question: "Who is this character?", image: "/images/characters/cloud.png", answers: ["cloud", "cloud strife"], category: "character-images" },
      { question: "Who is this character?", image: "/images/characters/bayonetta.png", answers: ["bayonetta"], category: "character-images" },
      { question: "Who is this character?", image: "/images/characters/ridley.png", answers: ["ridley"], category: "character-images" },
      { question: "Who is this character?", image: "/images/characters/king-k-rool.png", answers: ["king k rool", "k rool", "king k. rool"], category: "character-images" },
      { question: "Who is this character?", image: "/images/characters/isabelle.png", answers: ["isabelle"], category: "character-images" },
    ],
    hard: [
      { question: "Who is this character?", image: "/images/characters/roy.png", answers: ["roy"], category: "character-images" },
      { question: "Who is this character?", image: "/images/characters/lucas.png", answers: ["lucas"], category: "character-images" },
      { question: "Who is this character?", image: "/images/characters/ike.png", answers: ["ike"], category: "character-images" },
      { question: "Who is this character?", image: "/images/characters/robin.png", answers: ["robin"], category: "character-images" },
      { question: "Who is this character?", image: "/images/characters/corrin.png", answers: ["corrin"], category: "character-images" },
      { question: "Who is this character?", image: "/images/characters/simon.png", answers: ["simon", "simon belmont"], category: "character-images" },
      { question: "Who is this character?", image: "/images/characters/richter.png", answers: ["richter", "richter belmont"], category: "character-images" },
      { question: "Who is this character?", image: "/images/characters/king-dedede.png", answers: ["king dedede", "dedede"], category: "character-images" },
      { question: "Who is this character?", image: "/images/characters/meta-knight.png", answers: ["meta knight", "metaknight"], category: "character-images" },
      { question: "Who is this character?", image: "/images/characters/palutena.png", answers: ["palutena"], category: "character-images" },
      { question: "Who is this character?", image: "/images/characters/joker.png", answers: ["joker"], category: "character-images" },
      { question: "Who is this character?", image: "/images/characters/hero.png", answers: ["hero"], category: "character-images" },
      { question: "Who is this character?", image: "/images/characters/banjo-kazooie.png", answers: ["banjo and kazooie", "banjo & kazooie", "banjo kazooie"], category: "character-images" },
      { question: "Who is this character?", image: "/images/characters/terry.png", answers: ["terry", "terry bogard"], category: "character-images" },
      { question: "Who is this character?", image: "/images/characters/byleth.png", answers: ["byleth"], category: "character-images" },
      { question: "Who is this character?", image: "/images/characters/min-min.png", answers: ["min min", "minmin"], category: "character-images" },
      { question: "Who is this character?", image: "/images/characters/steve.png", answers: ["steve"], category: "character-images" },
      { question: "Who is this character?", image: "/images/characters/sephiroth.png", answers: ["sephiroth"], category: "character-images" },
    ]
  },
  'stage-images': {
    easy: [
      { question: "What stage is this?", image: "/images/stages/battlefield.png", answers: ["battlefield"], category: "stage-images" },
      { question: "What stage is this?", image: "/images/stages/final-destination.png", answers: ["final destination", "fd"], category: "stage-images" },
      { question: "What stage is this?", image: "/images/stages/peachs-castle.png", answers: ["peach's castle", "peachs castle", "peach castle"], category: "stage-images" },
      { question: "What stage is this?", image: "/images/stages/hyrule-castle.png", answers: ["hyrule castle"], category: "stage-images" },
      { question: "What stage is this?", image: "/images/stages/kongo-jungle.png", answers: ["kongo jungle"], category: "stage-images" },
      { question: "What stage is this?", image: "/images/stages/pokemon-stadium.png", answers: ["pokemon stadium"], category: "stage-images" },
      { question: "What stage is this?", image: "/images/stages/green-hill-zone.png", answers: ["green hill zone", "green hill"], category: "stage-images" },
      { question: "What stage is this?", image: "/images/stages/delfino-plaza.png", answers: ["delfino plaza"], category: "stage-images" },
      { question: "What stage is this?", image: "/images/stages/yoshis-island.png", answers: ["yoshi's island", "yoshis island", "yoshi island"], category: "stage-images" },
      { question: "What stage is this?", image: "/images/stages/new-donk-city.png", answers: ["new donk city hall", "new donk city"], category: "stage-images" },
    ],
    medium: [
      { question: "What stage is this?", image: "/images/stages/onett.png", answers: ["onett"], category: "stage-images" },
      { question: "What stage is this?", image: "/images/stages/mute-city.png", answers: ["mute city"], category: "stage-images" },
      { question: "What stage is this?", image: "/images/stages/corneria.png", answers: ["corneria"], category: "stage-images" },
      { question: "What stage is this?", image: "/images/stages/brinstar.png", answers: ["brinstar"], category: "stage-images" },
      { question: "What stage is this?", image: "/images/stages/fountain-of-dreams.png", answers: ["fountain of dreams"], category: "stage-images" },
      { question: "What stage is this?", image: "/images/stages/skyworld.png", answers: ["skyworld"], category: "stage-images" },
      { question: "What stage is this?", image: "/images/stages/warioware.png", answers: ["warioware inc", "warioware"], category: "stage-images" },
      { question: "What stage is this?", image: "/images/stages/norfair.png", answers: ["norfair"], category: "stage-images" },
      { question: "What stage is this?", image: "/images/stages/castle-siege.png", answers: ["castle siege"], category: "stage-images" },
      { question: "What stage is this?", image: "/images/stages/skyloft.png", answers: ["skyloft"], category: "stage-images" },
      { question: "What stage is this?", image: "/images/stages/boxing-ring.png", answers: ["boxing ring"], category: "stage-images" },
      { question: "What stage is this?", image: "/images/stages/gaur-plain.png", answers: ["gaur plain"], category: "stage-images" },
    ],
    hard: [
      { question: "What stage is this?", image: "/images/stages/suzaku-castle.png", answers: ["suzaku castle"], category: "stage-images" },
      { question: "What stage is this?", image: "/images/stages/midgar.png", answers: ["midgar"], category: "stage-images" },
      { question: "What stage is this?", image: "/images/stages/umbra-clock-tower.png", answers: ["umbra clock tower"], category: "stage-images" },
      { question: "What stage is this?", image: "/images/stages/great-plateau-tower.png", answers: ["great plateau tower"], category: "stage-images" },
      { question: "What stage is this?", image: "/images/stages/new-pork-city.png", answers: ["new pork city"], category: "stage-images" },
      { question: "What stage is this?", image: "/images/stages/palutenas-temple.png", answers: ["palutena's temple", "palutenas temple"], category: "stage-images" },
      { question: "What stage is this?", image: "/images/stages/draculas-castle.png", answers: ["dracula's castle", "draculas castle", "dracula castle"], category: "stage-images" },
      { question: "What stage is this?", image: "/images/stages/mementos.png", answers: ["mementos"], category: "stage-images" },
      { question: "What stage is this?", image: "/images/stages/spiral-mountain.png", answers: ["spiral mountain"], category: "stage-images" },
      { question: "What stage is this?", image: "/images/stages/kof-stadium.png", answers: ["king of fighters stadium", "kof stadium"], category: "stage-images" },
      { question: "What stage is this?", image: "/images/stages/garreg-mach.png", answers: ["garreg mach monastery", "garreg mach"], category: "stage-images" },
      { question: "What stage is this?", image: "/images/stages/spring-stadium.png", answers: ["spring stadium"], category: "stage-images" },
      { question: "What stage is this?", image: "/images/stages/minecraft-world.png", answers: ["minecraft world"], category: "stage-images" },
      { question: "What stage is this?", image: "/images/stages/northern-cave.png", answers: ["northern cave"], category: "stage-images" },
    ]
  }
};
